### ISSUE TITLE
引包错误

### ISSUE THREAD

**Issue by wxwall** [xkcoding/easy-rules-demo#1]
楼主可以把返回类 R 去掉，引用不到包

**Comment by xkcoding** [comment]
这个因为我是用的自己的 Magic-Starter 的包，暂时还未发布，只是在本地 install 了 - -
你暂时可以替换成自己的，把 Magic-Starter 相关的包修改下

**Comment by xkcoding** [comment]
已添加快照依赖的仓库地址，现在应该可以下载到啦~
@wxwall
